#!/usr/bin/env python

import os
import yaml
import h5py
import numpy as np

for o in range(26):
    m = o + 71
    dat_name = '../data/reduced/LkCa4_IGRINS_m{:03d}.hdf5'.format(m)
    path_out = 'm{:03d}/'.format(m)
    sf_out = 'm{:03d}/config.yaml'.format(m)
    
    f = open("m112/config.yaml")
    config = yaml.load(f)
    f.close()
    
    f=h5py.File(dat_name, "r")
    wls = f['wls'][:]
    f.close()
    
    config['data']['files'] = ['/home/gully/GitHub/welter/data/reduced/LkCa4_IGRINS_m{:03d}.hdf5'.format(m)]
    config['grid']['hdf5_path'] = '/home/gully/GitHub/welter/sf/m113/libraries/PHOENIX_IGRINS_m{:03d}.hdf5'.format(m)
    lb, ub = int(np.floor(wls[0])), int(np.ceil(wls[-1]))

    config['grid']['wl_range'] = [lb, ub]
    config['PCA']['path'] = '/home/gully/GitHub/welter/sf/m{:03d}/PHOENIX_IGRINS_H_PCA.hdf5'.format(m)
    config['name'] = 'LkCa4_m{:03d}'.format(m)
    config['Comments'] = 'LkCa4 single order: m = {}, autogenerated config file.'.format(m)
    config['data']['instruments'] =['IGRINS_K']
    print("{:03d}: {:.0f}  -  {:.0f}   {}".format(m, wls[0], wls[-1], dat_name))
    
    if m!=113:
        os.makedirs(path_out, exist_ok=True)
        with open(sf_out, mode='w') as outfile:
            outfile.write(yaml.dump(config))
            print('wrote to {}'.format(path_out))
    else:
        print('skipping 113')
