Comments: 'IGRINS H Band first trial

  '
PCA:
  path: /home/gully/GitHub/welter/sf/m113/PHOENIX_IGRINS_H_PCA.hdf5
  priors:
  - [2.0, 0.0075]
  - [2.0, 0.75]
  - [2.0, 0.75]
  threshold: 0.999
Phi: {l: 20.0, logAmp: -2.0, sigAmp: 1.0}
Phi_jump: {l: 0.25, logAmp: 0.01, sigAmp: 0.025}
Theta:
  Av: 0.0
  grid: [3500, 3.7, -0.21]
  logOmega: -0.35343
  vsini: 31.3808
  vz: 92.29
Theta_jump:
  Av: 0.01
  grid: [3, 0.003, 0.001]
  logOmega: 0.0003
  vsini: 0.05
  vz: 0.05
cheb_degree: 4
cheb_jump: 0.0001
data:
  files: [/home/gully/GitHub/welter/data/reduced/LkCa4_IGRINS_m113.hdf5]
  grid_name: PHOENIX
  instruments: [IGRINS_H]
  orders: [0]
grid:
  buffer: 30.0
  hdf5_path: /home/gully/GitHub/welter/sf/m113/libraries/PHOENIX_IGRINS_m114.hdf5
  key_name: t{0:.0f}g{1:.1f}z{2:.1f}
  parname: [temp, logg, Z]
  parrange:
  - [3500, 4300]
  - [3.5, 4.0]
  - [-0.5, 0.5]
  raw_path: /home/gully/GitHub/Starfish/libraries/raw/PHOENIX/
  wl_range: [15800, 15975]
name: LkCa4_m113
outdir: output/
plotdir: plots/
region_params: {logAmp: -2.0, sigma: 7.0}
sigma_clip: 4.0
