Comments: 'SYNTHETIC DATA simulating two-Temps: 3300 and 4100. The 4100 filling factor
  is 70 percent.'
PCA:
  path: /Users/gully/GitHub/welter/sf/m077/PHOENIX_IGRINS_H_PCA.hdf5
  priors:
  - [2.0, 0.0075]
  - [2.0, 0.75]
  - [2.0, 0.75]
  threshold: 0.999
Phi: {l: 25.0, logAmp: -1.9, sigAmp: 0.4}
Phi_jump: {l: 0.25, logAmp: 0.01, sigAmp: 0.025}
Theta:
  Av: 0.0
  grid: [4000.0, 3.7, 0.0]
  logOmega: -0.25
  vsini: 30.0
  vz: 90.0
Theta_jump:
  Av: 0.01
  grid: [10, 0.002, 0.002]
  logOmega: 0.0003
  vsini: 0.05
  vz: 0.05
cheb_degree: 4
cheb_jump: 0.0001
data:
  files: [/Users/gully/GitHub/welter/data/synthetic/LkCa4_Synthetic_sm077.hdf5]
  grid_name: PHOENIX
  instruments: [IGRINS_K]
  orders: [0]
grid:
  buffer: 30.0
  hdf5_path: /Users/gully/GitHub/welter/sf/m113/libraries/PHOENIX_IGRINS_m077.hdf5
  key_name: t{0:.0f}g{1:.1f}z{2:.1f}
  parname: [temp, logg, Z]
  parrange:
  - [3000, 4300]
  - [3.5, 4.0]
  - [-0.5, 0.5]
  raw_path: /Users/gully/GitHub/Starfish/libraries/raw/PHOENIX/
  wl_range: [23009, 23238]
name: LkCa4_sm077
outdir: output/
plotdir: plots/
region_params: {logAmp: -2.0, sigma: 7.0}
sigma_clip: 4.0
