Comments: 'LkCa4 H band, Big Kahuna!'
PCA:
  path: $WELTER/mf/exp02/PHOENIX_IGRINSords02_22_PCA.hdf5
  priors:
  - [2.0, 0.0075]
  - [2.0, 0.75]
  - [2.0, 0.75]
  threshold: 0.999
Phi: {l: 25.0, logAmp: -1.9, sigAmp: 0.4}
Phi_jump: {l: 0.2, logAmp: 0.02, sigAmp: 0.05}
Theta:
  Av: 0.0
  grid: [4100.0, 3.70, -0.1]
  logOmega: -0.73
  logOmega2: -0.24
  teff2: 3300.0
  vsini: 28.5
  vz: 12.0
Theta_jump:
  Av: 0.01
  grid: [20, 0.01, 0.01]
  logOmega: 0.001
  logOmega2: 0.001
  teff2: 40
  vsini: 0.1
  vz: 0.1
cheb_degree: 4
cheb_jump: 0.007
data:
  files: [$WELTER/data/reduced/LkCa4_IGRINS_H_clean.hdf5]
  grid_name: PHOENIX
  instruments: [IGRINS_H]
  orders: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
grid:
  buffer: 30.0
  hdf5_path: $WELTER/mf/exp02/PHOENIX_IGRINSords02_22_grid.hdf5
  key_name: t{0:.0f}g{1:.1f}z{2:.1f}
  parname: [temp, logg, Z]
  parrange:
  - [3000, 4300]
  - [3.5, 4.0]
  - [-0.5, 0.5]
  raw_path: $HOME/GitHub/Starfish/libraries/raw/PHOENIX/
  wl_range: [14900, 18000]
name: LkCa4_exp02
outdir: output/
plotdir: plots/
region_params: {logAmp: -2.0, sigma: 7.0}
sigma_clip: 4.0
