Comments: Mixture model with emcee order-by-order
PCA:
  path: $WELTER/sf/m089/PHX_IGR_2700-4500_K_PCA.hdf5
  priors:
  - [2.0, 0.0075]
  - [2.0, 0.75]
  - [2.0, 0.75]
  threshold: 0.999
Phi: {l: 25.0, logAmp: -1.9, sigAmp: 0.4}
Phi_jump: {l: 0.25, logAmp: 0.01, sigAmp: 0.025}
Theta:
  Av: 0.0
  grid: [4100.0, 3.8, 0.0]
  logOmega: -0.25
  logOmega2: -0.1
  teff2: 3300
  vsini: 30.0
  vz: 0.0
Theta_jump:
  Av: 0.01
  grid: [10, 0.002, 0.002]
  logOmega: 0.0003
  logOmega2: 0.0003
  teff2: 10
  vsini: 0.05
  vz: 0.05
cheb_degree: 4
cheb_jump: 0.0001
data:
  files: [$WELTER/data/reduced/LkCa4_IGRINS_m089.hdf5]
  grid_name: PHOENIX
  instruments: [IGRINS_K]
  orders: [0]
grid:
  air: true
  buffer: 30.0
  hdf5_path: $WELTER/sf/m089/libraries/PHX_IGR_2700-4500_m089.hdf5
  key_name: t{0:.0f}g{1:.1f}z{2:.1f}
  norm: true
  parname: [temp, logg, Z]
  parrange:
  - [2700, 4500]
  - [3.5, 4.0]
  - [-0.5, 0.5]
  raw_path: $Starfish/libraries/raw/PHOENIX/
  wl_range: [19958, 20157]
name: mix_emcee
outdir: output/
plotdir: plots/
region_params: {logAmp: -2.0, sigma: 7.0}
sigma_clip: 4.0
